-- LogsDB 데이터베이스 구조 내보내기
DROP DATABASE IF EXISTS LogsDB;

CREATE database LogsDB CHARACTER SET utf8 COLLATE utf8_unicode_ci;

-- 데이터베이스 변경
USE LogsDB;
CREATE TABLE LOGS
(
    USER_ID VARCHAR(20) NOT NULL,
    DATED DATETIME NOT NULL,
    LOGGER VARCHAR(50) NOT NULL,
    LEVEL VARCHAR(10) NOT NULL,
    MESSAGE VARCHAR(1000) NOT NULL
);

